### ISSUE TITLE
How about more control for compiler options?

### ISSUE THREAD

**Issue by MaxGraey** [SinaMFE/assemblyscript-typescript-loader#8]
Hi. Currently [AS main](https://github.com/SinaMFE/assemblyscript-typescript-loader/blob/master/src/index.js#L100) call with hardcoded options like `--optimize`, `--sourceMap`, `--validate`. But better allow user tuning this flags. See full list of supported flags and its values here: https://github.com/AssemblyScript/assemblyscript/wiki/Using-the-compiler

wdyt?

**Comment by happybang** [comment]
Sounds like a plan!
